# Generated by Django 4.1.2 on 2025-11-01 13:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EcosystemServiceConfig',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=255, unique=True, verbose_name='Nome do Serviço')),
                ('codigo', models.SlugField(max_length=100, unique=True, verbose_name='Código Único')),
                ('descricao', models.TextField(blank=True, verbose_name='Descrição')),
                ('formula', models.TextField(verbose_name='Fórmula Python')),
                ('coeficientes', models.JSONField(default=dict, verbose_name='Coeficientes')),
                ('valor_monetario_unitario', models.FloatField(default=0.0, verbose_name='Valor Monetário por Unidade (R$)')),
                ('unidade_medida', models.CharField(default='unidade', max_length=50, verbose_name='Unidade de Medida')),
                ('ativo', models.BooleanField(default=True, verbose_name='Serviço Ativo')),
                ('ordem_exibicao', models.IntegerField(default=0, verbose_name='Ordem de Exibição')),
                ('referencia_cientifica', models.CharField(blank=True, max_length=500, verbose_name='Referência Científica')),
                ('categoria', models.CharField(choices=[('SEQUESTRO', 'Sequestro/Armazenamento'), ('INTERCEPTACAO', 'Interceptação'), ('ENERGIA', 'Energia'), ('POLUICAO', 'Poluição'), ('OUTROS', 'Outros')], default='OUTROS', max_length=50, verbose_name='Categoria')),
                ('data_criacao', models.DateTimeField(auto_now_add=True)),
                ('data_atualizacao', models.DateTimeField(auto_now=True)),
                ('criado_por', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servicos_criados', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Configuração de Serviço Ecossistêmico',
                'verbose_name_plural': 'Configurações de Serviços Ecossistêmicos',
                'ordering': ['ordem_exibicao', 'nome'],
            },
        ),
        migrations.CreateModel(
            name='EcosystemServiceHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('acao', models.CharField(max_length=255, verbose_name='Ação Realizada')),
                ('valores_anteriores', models.JSONField(blank=True, null=True, verbose_name='Valores Anteriores')),
                ('valores_novos', models.JSONField(blank=True, null=True, verbose_name='Valores Novos')),
                ('observacao', models.TextField(blank=True, verbose_name='Observação')),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('servico', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='historico', to='main.ecosystemserviceconfig')),
                ('usuario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Histórico de Configuração',
                'verbose_name_plural': 'Históricos de Configurações',
                'ordering': ['-data'],
            },
        ),
    ]
